openapi: '3.0.2'
info:
  title: Thesis Service 
  description: This service allows for control of the system's thesis
  version: '1.0'
  contact:
    name: Katty Susana Gutierrez Villanueva
    email: katugutierrez17@gmail.com
servers:
  - url: https://linkDeployInHeroku/  

tags:
  - name: Thesis
    description: Everything about thesis
        
paths:
  #Modulo de Tesis  
  /thesis:
    get:
      tags:
        - Thesis      
      summary: Find all thesis          
      operationId: index
      responses:      
        '200':
          $ref: components/responses/responses.yml#/ShowThesis         
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
          
          
    post:
      tags:
        - Thesis
      summary: Add a new thesis to the system
      operationId: store
      requestBody:
        description: Thesis to add to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ThesisInformationPayload
      responses:      
        '201':
          $ref: components/responses/responses.yml#/CreatedThesis       
        '404':          
          $ref: components/responses/responses.yml#/NotFound
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 

  /thesis/{id}:
    get:
      tags:
        - Thesis
      summary: Find a thesis
      operationId: show
      parameters:
        - $ref: components/parameters/parameters.yml#/id
      responses:
        '200':
          $ref: components/responses/responses.yml#/ShowOneThesis      
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
    put: 
      tags:
        - Thesis
      summary: Update an existing thesis
      operationId: update
      parameters: 
        - $ref: components/parameters/parameters.yml#/id
      requestBody:
        description: Thesis to update to the system
        content:
          x-www-form-urlencoded:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ThesisPayload
      responses:
        '201':
          $ref: components/responses/responses.yml#/UpdateThesis
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntity           

    delete:
      tags:
        - Thesis
      summary: Delete an existing thesis
      operationId: destroy
      parameters:
        - $ref: components/parameters/parameters.yml#/id
      responses:
        '200':
          $ref: components/responses/responses.yml#/DeleteThesis    
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 

  /thesis/search:
    get:
      tags:
        - Thesis
      summary: Search for thesis by parameter
      operationId: searchTesis
      parameters:
        - $ref: components/parameters/parameters.yml#/title
        - $ref: components/parameters/parameters.yml#/clasification
        - $ref: components/parameters/parameters.yml#/year
        - $ref: components/parameters/parameters.yml#/keywords
        - $ref: components/parameters/parameters.yml#/author_name
        - $ref: components/parameters/parameters.yml#/adviser
      responses:
        '200':
          $ref: components/responses/responses.yml#/ShowThesis      
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated

  /thesis/pagination:
    get:
      tags:
        - Thesis
      summary: Recover a certain number of thesis per page
      operationId: pagThesis
      parameters:
        - $ref: components/parameters/parameters.yml#/page
        - $ref: components/parameters/parameters.yml#/limit
      responses:
        '200':
          $ref: components/responses/responses.yml#/ShowThesisPerPage      
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated

  /thesis/{id}/information:
    get:
      tags:
        - Thesis
      summary: Get all information and copies about a thesis
      operationId: showInformationThesis
      parameters:
        - $ref: components/parameters/parameters.yml#/id
      responses:
        '200':
          $ref: components/responses/responses.yml#/ShowInformationThesis   
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated

  /thesis/{id}/copies:     
    post:
      tags:
        - Thesis
      summary: Add a new thesis copy to the system
      operationId: store
      parameters:
        - $ref: components/parameters/parameters.yml#/id
      requestBody:
        description: thesis copy to add to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ThesisCopyPayload
      responses:      
        '201':
          $ref: components/responses/responses.yml#/CreatedThesisCopy
        '404':          
          $ref: components/responses/responses.yml#/NotFound
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 

  /thesis/{id}/copies/{id_copy}:
    get:
      tags:
        - Thesis
      summary: Get information about a copy of thesis
      operationId: showThesisCopy
      parameters:
        - $ref: components/parameters/parameters.yml#/id
        - $ref: components/parameters/parameters.yml#/id_copy
      responses:
        '200':
          $ref: components/responses/responses.yml#/ShowThesisCopy
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
    put: 
        tags:
          - Thesis
        summary: Update a thesis copy
        operationId: update
        parameters: 
          - $ref: components/parameters/parameters.yml#/id
          - $ref: components/parameters/parameters.yml#/id_copy
        requestBody:
          description: Thesis copy to update to the system
          content:
            x-www-form-urlencoded:
              schema:
                $ref: components/schemas/payloads/payload.yml#/ThesisCopyPayload
        responses:
          '201':
            $ref: components/responses/responses.yml#/UpdateThesisCopy
          '404':          
            $ref: components/responses/responses.yml#/NotFound 
          '405':
            $ref: components/responses/responses.yml#/MethodNotAllowed           
          '401':
            $ref: components/responses/responses.yml#/Unauthenticated 
          '422':
            $ref: components/responses/responses.yml#/UnprocessableEntity
    
    delete:
      tags:
        - Thesis
      summary: Delete a thesis copy
      operationId: destroy
      parameters:
        - $ref: components/parameters/parameters.yml#/id
        - $ref: components/parameters/parameters.yml#/id_copy
      responses:
        '200':
          $ref: components/responses/responses.yml#/DeleteThesisCopy
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 

      
# Aplicar la API key globalmente a todas las operaciones 
security:
  - Authorization: []
            

components:
      
  # SECURITY
  # Contiene todos los tipos de seguridad para el uso del servicio  
  securitySchemes:
    # AUTHORIZATION:
    # Permite el uso del servicio mediante el registro de una api key enviado en el header
    # con el nombre Authorization, por ejemplo: Authorization EJm9IExSA9rv3N9uCVfIhNRdNOMUSe8w
    # estas cadenas serán colocadas en el archivo de configuración del servicio y restringido mediante un middleware
    Authorization:
      type: apiKey
      name: Authorization
      in: header 
