
  # PARAMETERS
  #Contiene todos los parámetros que serán utilizados en una petición http ya sea que sea enviado
  #por el header, path, query o cache  
    id:
      name: id
      in: path
      required: true
      description: Thesis id 
      schema:
        type: integer
    id_copy:
      name: id_copy
      in: path
      required: true
      description: Thesis Copy id
      schema:
        type: integer
    page:
      name: page
      in: query
      required: false
      description: The number of page
      schema:
        type: integer
    limit:
      name: limit
      in: query
      required: false
      description: The numbers of items to return for page
      schema:
        type: integer
    title:
      name: title
      in: query
      required: false
      description: Thesis title
      schema:
        type: text
    clasification:
      name: clasification
      in: query
      required: false
      description: Thesis clasification
      schema:
        type: string
    year:
      name: year
      in: query
      required: false
      description: Thesis year
      schema:
        type: string
    keywords:
      name: keywords
      in: query
      required: false
      description: Thesis keywords
      schema:
        type: text
    author_id:
      name: author_id
      in: query
      required: false
      description: Thesis author id
      schema:
        type: integer
    adviser:
      name: adviser
      in: query
      required: false
      description: Thesis adviser
      schema:
        type: string